version: '2.1'

services:

  galera:
    depends_on:
      clustercontrol:
        condition: service_healthy
    image: severalnines/centos-ssh
    ports:
      - 3306
    environment:
      CLUSTER_TYPE: "galera"
      CLUSTER_NAME: "Galera_Docker"
      INITIAL_CLUSTER_SIZE: 3
      DB_ROOT_PASSWORD: "mypassword123"
    networks:
      - galera_cc

  clustercontrol:
    image: severalnines/clustercontrol:nightly
    ports:
      - 5000:80
    networks:
      - galera_cc
    healthcheck:
      test: "exit 0"

networks:
  galera_cc:
    driver: bridge
