apiVersion: v1
kind: Service
metadata:
  name: cc-galera
  labels:
    app: cc-galera
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: cc-galera
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cc-galera
spec:
  serviceName: cc-galera
  replicas: 3
  template:
    metadata:
      labels:
        app: cc-galera
    spec:
      containers:
      - name: galera
        image: severalnines/centos-ssh
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: CLUSTER_TYPE
          value: galera
        - name: CLUSTER_NAME
          value: Galera_Docker
        - name: INITIAL_CLUSTER_SIZE
          value: "3"
        - name: DB_ROOT_PASSWORD
          value: mypassword123
        - name: VENDOR
          value: mariadb
        - name: PROVIDER_VERSION
          value: "10.1"
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
