apiVersion: v1
kind: Service
metadata:
  name: cc-galera
  labels:
    app: cc-galera
spec:
  type: NodePort
  ports:
  - name: mysql
    nodePort: 30015
    port: 3306
  selector:
    app: cc-galera
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cc-galera
  labels:
    app: cc-galera
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cc-galera
    spec:
      containers:
      - name: galera
        image: severalnines/centos-ssh
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: CLUSTER_TYPE
          value: galera
        - name: CLUSTER_NAME
          value: Galera_Docker
        - name: INITIAL_CLUSTER_SIZE
          value: "3"
        - name: DB_ROOT_PASSWORD
          value: mypassword123
        - name: VENDOR
          value: mariadb
        - name: PROVIDER_VERSION
          value: "10.1"
