apiVersion: v1
kind: Service
metadata:
  name: cc-haproxy
  labels:
    app: cc-haproxy
spec:
  type: NodePort
  ports:
  - name: mysql
    nodePort: 30016
    port: 3307
  selector:
    app: cc-haproxy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cc-haproxy
  labels:
    app: cc-haproxy
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cc-haproxy
    spec:
      containers:
      - name: haproxy
        image: severalnines/centos-ssh
        ports:
        - name: mysql-lb
          containerPort: 3307
        env:
        - name: AUTO_DEPLOYMENT
          value: "0"
